# Generated by Django 5.2.7 on 2025-11-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_userprofile_avatar_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, choices=[('Philippines', 'Philippines'), ('United States', 'United States'), ('United Kingdom', 'United Kingdom'), ('Canada', 'Canada'), ('Australia', 'Australia'), ('Japan', 'Japan'), ('China', 'China'), ('Singapore', 'Singapore'), ('Malaysia', 'Malaysia'), ('Thailand', 'Thailand'), ('Indonesia', 'Indonesia'), ('South Korea', 'South Korea'), ('India', 'India'), ('Germany', 'Germany'), ('France', 'France'), ('Italy', 'Italy'), ('Spain', 'Spain'), ('Brazil', 'Brazil'), ('Mexico', 'Mexico'), ('Argentina', 'Argentina'), ('New Zealand', 'New Zealand'), ('United Arab Emirates', 'United Arab Emirates'), ('Saudi Arabia', 'Saudi Arabia'), ('Other', 'Other')], help_text='Location/Country', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(choices=[('UTC', 'UTC (Coordinated Universal Time)'), ('Asia/Manila', 'Philippines (Manila)'), ('America/New_York', 'United States (Eastern Time)'), ('America/Chicago', 'United States (Central Time)'), ('America/Denver', 'United States (Mountain Time)'), ('America/Los_Angeles', 'United States (Pacific Time)'), ('Europe/London', 'United Kingdom (London)'), ('Europe/Paris', 'France (Paris)'), ('Europe/Berlin', 'Germany (Berlin)'), ('Europe/Rome', 'Italy (Rome)'), ('Europe/Madrid', 'Spain (Madrid)'), ('Asia/Tokyo', 'Japan (Tokyo)'), ('Asia/Shanghai', 'China (Shanghai)'), ('Asia/Hong_Kong', 'Hong Kong'), ('Asia/Singapore', 'Singapore'), ('Asia/Bangkok', 'Thailand (Bangkok)'), ('Asia/Jakarta', 'Indonesia (Jakarta)'), ('Asia/Kuala_Lumpur', 'Malaysia (Kuala Lumpur)'), ('Asia/Seoul', 'South Korea (Seoul)'), ('Asia/Dubai', 'United Arab Emirates (Dubai)'), ('Asia/Riyadh', 'Saudi Arabia (Riyadh)'), ('Asia/Kolkata', 'India (Mumbai/Delhi)'), ('Australia/Sydney', 'Australia (Sydney)'), ('Australia/Melbourne', 'Australia (Melbourne)'), ('Pacific/Auckland', 'New Zealand (Auckland)'), ('America/Toronto', 'Canada (Toronto)'), ('America/Vancouver', 'Canada (Vancouver)'), ('America/Mexico_City', 'Mexico (Mexico City)'), ('America/Sao_Paulo', 'Brazil (São Paulo)'), ('America/Buenos_Aires', 'Argentina (Buenos Aires)')], default='UTC', help_text="User's preferred timezone", max_length=100),
        ),
    ]
