# Generated by Django 5.2.7 on 2025-12-05 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField(help_text='Stored in UTC')),
                ('end_time', models.DateTimeField(help_text='Stored in UTC')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('invite_participants', models.TextField(blank=True, help_text='Comma-separated email addresses of participants')),
                ('invitation_link', models.CharField(blank=True, help_text='Generated invitation link for the event', max_length=500)),
                ('external_calendar_id', models.CharField(blank=True, help_text='ID from external calendar sync', max_length=200, null=True)),
                ('external_calendar_type', models.CharField(blank=True, choices=[('google', 'Google Calendar'), ('outlook', 'Outlook'), ('ical', 'iCal')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('reminder', 'Reminder'), ('event', 'Event'), ('system', 'System')], default='reminder', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('delivery_method', models.CharField(choices=[('email', 'Email'), ('web', 'Web'), ('both', 'Both')], default='web', max_length=50)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='homepage.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('reminder_time', models.DateTimeField(help_text='When to send the reminder (UTC)')),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='homepage.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['reminder_time'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(choices=[('UTC', 'UTC (Coordinated Universal Time)'), ('Asia/Manila', 'Philippines (Manila)'), ('America/New_York', 'United States (Eastern Time)'), ('America/Chicago', 'United States (Central Time)'), ('America/Denver', 'United States (Mountain Time)'), ('America/Los_Angeles', 'United States (Pacific Time)'), ('Europe/London', 'United Kingdom (London)'), ('Europe/Paris', 'France (Paris)'), ('Europe/Berlin', 'Germany (Berlin)'), ('Europe/Rome', 'Italy (Rome)'), ('Europe/Madrid', 'Spain (Madrid)'), ('Asia/Tokyo', 'Japan (Tokyo)'), ('Asia/Shanghai', 'China (Shanghai)'), ('Asia/Hong_Kong', 'Hong Kong'), ('Asia/Singapore', 'Singapore'), ('Asia/Bangkok', 'Thailand (Bangkok)'), ('Asia/Jakarta', 'Indonesia (Jakarta)'), ('Asia/Kuala_Lumpur', 'Malaysia (Kuala Lumpur)'), ('Asia/Seoul', 'South Korea (Seoul)'), ('Asia/Dubai', 'United Arab Emirates (Dubai)'), ('Asia/Riyadh', 'Saudi Arabia (Riyadh)'), ('Asia/Kolkata', 'India (Mumbai/Delhi)'), ('Australia/Sydney', 'Australia (Sydney)'), ('Australia/Melbourne', 'Australia (Melbourne)'), ('Pacific/Auckland', 'New Zealand (Auckland)'), ('America/Toronto', 'Canada (Toronto)'), ('America/Vancouver', 'Canada (Vancouver)'), ('America/Mexico_City', 'Mexico (Mexico City)'), ('America/Sao_Paulo', 'Brazil (São Paulo)'), ('America/Buenos_Aires', 'Argentina (Buenos Aires)')], default='UTC', help_text="User's preferred timezone", max_length=100)),
                ('email_notifications', models.BooleanField(default=True)),
                ('web_notifications', models.BooleanField(default=True)),
                ('bio', models.TextField(blank=True, help_text='Short biography or description', max_length=500)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=20)),
                ('location', models.CharField(blank=True, choices=[('Philippines', 'Philippines'), ('United States', 'United States'), ('United Kingdom', 'United Kingdom'), ('Canada', 'Canada'), ('Australia', 'Australia'), ('Japan', 'Japan'), ('China', 'China'), ('Singapore', 'Singapore'), ('Malaysia', 'Malaysia'), ('Thailand', 'Thailand'), ('Indonesia', 'Indonesia'), ('South Korea', 'South Korea'), ('India', 'India'), ('Germany', 'Germany'), ('France', 'France'), ('Italy', 'Italy'), ('Spain', 'Spain'), ('Brazil', 'Brazil'), ('Mexico', 'Mexico'), ('Argentina', 'Argentina'), ('New Zealand', 'New Zealand'), ('United Arab Emirates', 'United Arab Emirates'), ('Saudi Arabia', 'Saudi Arabia'), ('Other', 'Other')], help_text='Location/Country', max_length=100)),
                ('avatar', models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user', 'start_time'], name='homepage_ev_user_id_337304_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='homepage_no_user_id_9c2d2d_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['user', 'reminder_time', 'is_sent'], name='homepage_re_user_id_aee28e_idx'),
        ),
    ]
