# Generated by Django 5.2.7 on 2025-12-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='invitation_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], help_text='Status for event invitations', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reminder', 'Reminder'), ('event', 'Event'), ('event_invitation', 'Event Invitation'), ('system', 'System')], default='reminder', max_length=50),
        ),
    ]
